### ISSUE TITLE
Manning coupon code expired! :(

### ISSUE THREAD

**Issue by Advaya-Labs** [chrisvoncsefalvay/juliabook#3]
Hi,

Wanted to take advantage of the 50% off coupon code MLCSEFAL but looks like it expired. 
Could you please let me know if there is another coupon.

Thanks.

**Comment by chrisvoncsefalvay** [comment]
Closed as duplicate of (Issue 2)[https://github.com/chrisvoncsefalvay/juliabook/issues/2].
